<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import {
  NButton,
  NCard,
  NSelect,
  NSwitch,
  NInput,
  useMessage,
} from 'naive-ui'
import { useI18n } from 'vue-i18n'
import { useKanbanStore } from '@/stores/hermes/kanban'
import type { KanbanOrchestrationProfile } from '@/api/hermes/kanban'

const { t } = useI18n()
const message = useMessage()
const store = useKanbanStore()

const expanded = ref(false)
const busy = ref<Record<string, 'save' | 'auto' | null>>({})
const panelMsg = ref<{ ok: boolean; text: string } | null>(null)

const settings = computed(() => store.orchestration)
const profiles = computed(() => store.orchestration?.profiles || [])
const autoOn = computed(() => !!(settings.value && settings.value.auto_decompose))

const profileOptions = computed(() => {
  const list = profiles.value.map((p: KanbanOrchestrationProfile) => ({
    label: p.name,
    value: p.name,
  }))
  return [{ label: t('kanban.orchestration.defaultOption', '(default)'), value: '' }, ...list]
})

async function saveSettings(patch: { orchestrator_profile?: string; default_assignee?: string; auto_decompose?: boolean }) {
  panelMsg.value = null
  try {
    const result = await store.saveOrchestrationSettings(patch)
    const successText = t('kanban.orchestration.saved', { defaultValue: 'Settings saved' })
    message.success(successText)
    panelMsg.value = { ok: true, text: successText }
    return result
  } catch (err: any) {
    const text = err?.message || t('kanban.orchestration.saveFailed', { defaultValue: 'Save failed' })
    message.error(text)
    panelMsg.value = { ok: false, text }
    throw err
  }
}

async function saveProfileDescription(name: string, description: string) {
  busy.value[name] = 'save'
  panelMsg.value = null
  try {
    await store.saveProfileDescription(name, description)
    const successText = t('kanban.orchestration.descriptionSaved', { name, defaultValue: 'Description saved for {name}' })
    message.success(successText)
    panelMsg.value = { ok: true, text: successText }
  } catch (err: any) {
    const text = err?.message || t('kanban.orchestration.saveFailed', { defaultValue: 'Save failed' })
    message.error(text)
    panelMsg.value = { ok: false, text }
  } finally {
    busy.value[name] = null
  }
}

async function autoGenerateDescription(name: string, overwrite = true) {
  busy.value[name] = 'auto'
  panelMsg.value = null
  try {
    const res = await store.autoGenerateProfileDescription(name, overwrite)
    if (res.ok) {
      const successText = t('kanban.orchestration.autoGenerated', { name, defaultValue: 'Auto-generated description for {name}' })
      message.success(successText)
      panelMsg.value = { ok: true, text: successText }
    } else {
      const text = t('kanban.orchestration.autoGenerateFailed', { defaultValue: 'Auto-generate failed' })
      message.error(text)
      panelMsg.value = { ok: false, text }
    }
  } catch (err: any) {
    const text = err?.message || t('kanban.orchestration.autoGenerateFailed', { defaultValue: 'Auto-generate failed' })
    message.error(text)
    panelMsg.value = { ok: false, text }
  } finally {
    busy.value[name] = null
  }
}

function toggleAutoDecompose() {
  if (!settings.value) return
  saveSettings({ auto_decompose: !autoOn.value })
}

function onOrchestratorProfileChange(value: string) {
  saveSettings({ orchestrator_profile: value || undefined })
}

function onDefaultAssigneeChange(value: string) {
  saveSettings({ default_assignee: value || undefined })
}

// Load orchestration settings on mount
watch(() => store.selectedBoard, () => {
  store.fetchOrchestration()
}, { immediate: true })
</script>

<template>
  <div class="kanban-orchestration-panel">
    <!-- Collapsed mode: mode pill + expand button -->
    <div v-if="!expanded" class="orchestration-collapsed">
      <NButton
        size="tiny"
        :type="autoOn ? 'success' : 'default'"
        :ghost="autoOn"
        round
        @click="toggleAutoDecompose"
        :title="autoOn
          ? t('kanban.orchestration.autoTitle', 'Orchestration: Auto — the dispatcher decomposes new triage tasks automatically every tick. Click to switch to Manual.')
          : t('kanban.orchestration.manualTitle', 'Orchestration: Manual — triage tasks stay in triage until you click Decompose on each card. Click to switch to Auto.')"
      >
        {{ t('kanban.orchestration.mode', 'Orchestration') }}:
        <strong>{{ settings === null ? '…' : (autoOn ? t('kanban.orchestration.auto', 'Auto') : t('kanban.orchestration.manual', 'Manual')) }}</strong>
      </NButton>
      <NButton
        size="tiny"
        text
        @click="expanded = true"
        :title="t('kanban.orchestration.expandTitle', 'Configure the kanban orchestrator (profile picker, default assignee, auto-decompose, profile descriptions)')"
      >
        {{ t('kanban.orchestration.settings', '▸ Orchestration settings') }}
      </NButton>
    </div>

    <!-- Expanded mode: full panel -->
    <NCard v-else size="small" class="orchestration-card">
      <div class="orchestration-header">
        <NButton size="tiny" text @click="expanded = false">
          {{ t('kanban.orchestration.settings', '▾ Orchestration settings') }}
        </NButton>
        <NButton
          size="tiny"
          :type="autoOn ? 'success' : 'default'"
          :ghost="autoOn"
          round
          @click="toggleAutoDecompose"
        >
          {{ t('kanban.orchestration.mode', 'Orchestration') }}:
          <strong>{{ autoOn ? t('kanban.orchestration.auto', 'Auto') : t('kanban.orchestration.manual', 'Manual') }}</strong>
        </NButton>
        <NButton size="tiny" @click="store.fetchOrchestration()">
          {{ t('kanban.orchestration.reload', 'Reload') }}
        </NButton>
      </div>

      <div v-if="panelMsg" class="orchestration-msg" :class="panelMsg.ok ? 'msg-ok' : 'msg-err'">
        {{ panelMsg.text }}
      </div>

      <div v-if="settings" class="orchestration-grid">
        <!-- Orchestrator profile -->
        <div class="orchestration-field">
          <label class="field-label">{{ t('kanban.orchestration.orchestratorProfile', 'Orchestrator profile') }}</label>
          <NSelect
            size="small"
            :value="settings.orchestrator_profile || ''"
            :options="profileOptions"
            @update:value="onOrchestratorProfileChange"
          />
          <div class="field-hint">
            {{ t('kanban.orchestration.resolved', 'Resolved') }}: {{ settings.orchestrator_profile || t('kanban.orchestration.default', 'default') }}
          </div>
        </div>

        <!-- Default assignee -->
        <div class="orchestration-field">
          <label class="field-label">{{ t('kanban.orchestration.defaultAssignee', 'Default assignee') }}</label>
          <NSelect
            size="small"
            :value="settings.default_assignee || ''"
            :options="profileOptions"
            @update:value="onDefaultAssigneeChange"
          />
          <div class="field-hint">
            {{ t('kanban.orchestration.resolved', 'Resolved') }}: {{ settings.default_assignee || t('kanban.orchestration.default', 'default') }}
          </div>
        </div>

        <!-- Auto-decompose toggle -->
        <div class="orchestration-field">
          <label class="field-label">{{ t('kanban.orchestration.orchestrationMode', 'Orchestration mode') }}</label>
          <div class="switch-row">
            <NSwitch
              :value="autoOn"
              @update:value="(checked: boolean) => saveSettings({ auto_decompose: checked })"
            />
            <span class="switch-label">{{ t('kanban.orchestration.autoDecompose', 'Auto-decompose triage tasks') }}</span>
          </div>
          <div class="field-hint">
            {{ autoOn
              ? t('kanban.orchestration.autoHint', 'The dispatcher decomposes new triage tasks automatically.')
              : t('kanban.orchestration.manualHint', 'Triage tasks stay in triage until you click Decompose.')
            }}
          </div>
        </div>
      </div>

      <div v-else class="orchestration-loading">
        {{ t('kanban.orchestration.loading', 'Loading…') }}
      </div>

      <!-- Profile descriptions -->
      <div class="profile-descriptions">
        <label class="field-label">{{ t('kanban.orchestration.profileDescriptions', 'Profile descriptions') }}</label>
        <div class="field-hint">
          {{ t('kanban.orchestration.profileDescriptionsHint', 'Descriptions guide the decomposer\'s routing. Click ⚗ to auto-generate, or edit and save.') }}
        </div>

        <div v-if="profiles.length === 0" class="no-profiles">
          {{ t('kanban.orchestration.noProfiles', 'No profiles installed.') }}
        </div>

        <div v-else class="profile-list">
          <div
            v-for="profile in profiles"
            :key="profile.name"
            class="profile-row"
            :style="{ borderColor: profile.description ? '#888' : '#cc6' }"
          >
            <div class="profile-header">
              <span class="profile-name">{{ profile.name }}</span>
              <span v-if="profile.name === (settings?.orchestrator_profile || '')" class="profile-tag default">
                {{ t('kanban.orchestration.defaultTag', 'default') }}
              </span>
            </div>
            <div class="profile-actions">
              <NInput
                size="small"
                :value="profile.description || ''"
                :placeholder="t('kanban.orchestration.descriptionPlaceholder', 'What is this profile good at?')"
                @update:value="(val: string) => profile.description = val"
              />
              <NButton
                size="tiny"
                :disabled="!!busy[profile.name] || (profile.description || '') === (store.orchestration?.profiles.find(p => p.name === profile.name)?.description || '')"
                :loading="busy[profile.name] === 'save'"
                @click="saveProfileDescription(profile.name, profile.description || '')"
                :title="t('kanban.orchestration.saveDescriptionTitle', 'Save the description above as user-authored')"
              >
                {{ busy[profile.name] === 'save' ? t('kanban.orchestration.saving', 'Saving…') : t('kanban.orchestration.save', 'Save') }}
              </NButton>
              <NButton
                size="tiny"
                :disabled="!!busy[profile.name]"
                :loading="busy[profile.name] === 'auto'"
                @click="autoGenerateDescription(profile.name, true)"
                :title="t('kanban.orchestration.autoGenerateTitle', 'Auto-generate a description from this profile\'s skills and model')"
              >
                {{ busy[profile.name] === 'auto' ? t('kanban.orchestration.generating', 'Generating…') : '⚗ ' + t('kanban.orchestration.auto', 'Auto') }}
              </NButton>
            </div>
          </div>
        </div>
      </div>
    </NCard>
  </div>
</template>

<style scoped>
.kanban-orchestration-panel {
  margin-bottom: 12px;
}

.orchestration-collapsed {
  display: flex;
  align-items: center;
  gap: 12px;
  font-size: 12px;
}

.orchestration-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 12px;
  flex-wrap: wrap;
}

.orchestration-msg {
  padding: 6px 10px;
  border-radius: 4px;
  font-size: 12px;
  margin-bottom: 12px;
}

.msg-ok {
  background: rgba(24, 160, 88, 0.1);
  color: #18a058;
  border: 1px solid rgba(24, 160, 88, 0.2);
}

.msg-err {
  background: rgba(208, 48, 80, 0.1);
  color: #d03050;
  border: 1px solid rgba(208, 48, 80, 0.2);
}

.orchestration-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 16px;
  margin-bottom: 16px;
}

.orchestration-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.field-label {
  font-size: 12px;
  color: var(--n-text-color-3);
}

.field-hint {
  font-size: 11px;
  color: var(--n-text-color-3);
}

.switch-row {
  display: flex;
  align-items: center;
  gap: 8px;
  height: 32px;
}

.switch-label {
  font-size: 12px;
}

.orchestration-loading {
  font-size: 12px;
  color: var(--n-text-color-3);
  padding: 8px 0;
}

.profile-descriptions {
  border-top: 1px solid var(--n-border-color);
  padding-top: 12px;
}

.no-profiles {
  font-size: 12px;
  color: var(--n-text-color-3);
  padding: 8px 0;
}

.profile-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-top: 8px;
}

.profile-row {
  border-left: 2px solid #888;
  padding-left: 8px;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.profile-header {
  display: flex;
  align-items: center;
  gap: 8px;
}

.profile-name {
  font-size: 12px;
  font-weight: 600;
}

.profile-tag {
  font-size: 10px;
  padding: 1px 6px;
  border-radius: 4px;
  background: var(--n-tag-color);
  color: var(--n-text-color-2);
}

.profile-tag.default {
  background: rgba(24, 160, 88, 0.15);
  color: #18a058;
}

.profile-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.profile-actions .n-input {
  flex: 1;
}
</style>
